adding interfaces
tulibraries/ansible-role-networking pull request #5
Opened 2019-07-26 17:47 UTC by cmharlow

2019-07-26 17:53 UTC, bibliotechy approved these changes

2019-07-26 18:00 UTC, bibliotechy requested changes
Actually, now that I look at the failed test, won't this break every other playbook where we defined the `enabled_zones` variable, but it doesn't include the `trusted_interfaces` keys?

Maybe this (and all of the tasks dependent on a key being defined) should only run if the key is defined?

2019-07-30 12:57 UTC, cmharlow commented
fucking variables. fixing tests.

2019-07-30 13:07 UTC, cmharlow commented
Tagged a new major version to highlight breaking changes in variable management. All current users of this role should be using pinned versions.

2021-05-07 17:24 UTC, closed without merging